### ISSUE TITLE
Could not see the toggle to change the row color from red to green

### ISSUE THREAD

**Issue by PhDLuffy** [zotero/make-it-red#3]
m1 mac mini，macos 13.4.1，zotero 7.0.0，make-it-red 2.0

I tried the make-it-red plugin，I found the row change color to red. 

![image-20230702231506113](https://fastly.jsdelivr.net/gh/PhDLuffy/PicGo@master/img/202307022315127.png)

but there is not a toggle to change the color red to green which i found in the code.

![image-20230702231727367](https://fastly.jsdelivr.net/gh/PhDLuffy/PicGo@master/img/202307022317385.png)

I don't know why. 

I am curious of this because I have another plugin for zotero7 works well background but no front edit menu of the plugin on the pane.

**Comment by dstillman** [comment]
The toggle is in the View menu.

**Comment by PhDLuffy** [comment]
@dstillman you are right, it works well, thank you very much.
