### ISSUE TITLE
The code is not functioning properly.

### ISSUE THREAD

**Issue by dbcoffee** [zotero/make-it-red#7]
After installing the plugin through the source code mode（follow [plugin_development](https://www.zotero.org/support/dev/client_coding/plugin_development)), the item color turned red, while other sections remained unchanged. I couldn't find any logs in Zotero's error console, and both alert() and log() functions didn't work properly. What could be the problem?

**Comment by dstillman** [comment]
Please post development questions to the dev list.

Make sure you're testing with all other plugins disabled.
